name: Invalidate CloudFront Cache
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  invalidate:
    name: Invalidate CloudFront Cache
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_PROD_ID }}:role/GithubActionsRole"
          role-session-name: "GithubActions-CloudFrontInvalidation"

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

          echo "CloudFront cache invalidation created for all paths (/*)"
