name: Main
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml

  deploy:
    name: Deploy Website
    needs: verify
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/local_deploy.yml
    secrets: inherit
